### ISSUE TITLE
How to calculate MMD loss?

### ISSUE THREAD

**Issue by xmfbit** [TuSimple/neuron-selectivity-transfer#1]
Hi, @huangzehao  Thanks for the open source of NST method. But I am confused about the computing of MMD loss: https://github.com/TuSimple/neuron-selectivity-transfer/blob/master/symbol/transfer.py#L37. 
![mmd](https://user-images.githubusercontent.com/6002490/40279470-a14d23a0-5c75-11e8-8dff-66723063aa08.jpg)

And I wrote some code to check it. The MMD loss should be 0 if `X` and `Y` are the same, right? But the result of your code is not 0 (obviously `s - 2*s` cannot be 0).

```
import mxnet as mx
## copied from transfer.py, change it to mx.nd
def get_mmd(s, t):
    s = mx.nd.L2Normalization(s, mode='spatial')
    sv = mx.nd.Reshape(s, shape=(0,0,-1))
    svt = mx.nd.transpose(sv, axes=(0,2,1))
    sm = mx.nd.batch_dot(lhs=sv, rhs=svt)
    sm2 = mx.nd.square(sm)
    smm = mx.nd.mean(sm2, axis=(1,2))

    t = mx.nd.L2Normalization(t, mode='spatial')
    tv = mx.nd.Reshape(t, shape=(0,0,-1))
    tvt = mx.nd.transpose(tv, axes=(0,2,1))
    tm = mx.nd.batch_dot(lhs=sv, rhs=tvt)
    tm = mx.nd.square(tm)
    tmm = mx.nd.mean(tm, axis=(1,2))
    diff = smm - 2 * tmm
    return diff

def get_mmd2(s, t):
    s = mx.nd.L2Normalization(s, mode='spatial')
    sv = mx.nd.Reshape(s, shape=(0,0,-1))
    svt = mx.nd.transpose(sv, axes=(0,2,1))
    sm = mx.nd.batch_dot(lhs=sv, rhs=svt)
    sm2 = mx.nd.square(sm)
    smm = mx.nd.mean(sm2, axis=(1,2))

    t = mx.nd.L2Normalization(t, mode='spatial')
    tv = mx.nd.Reshape(t, shape=(0,0,-1))
    tvt = mx.nd.transpose(tv, axes=(0,2,1))
    tm = mx.nd.batch_dot(lhs=sv, rhs=tvt)
    tm = mx.nd.square(tm)
    tmm = mx.nd.mean(tm, axis=(1,2))

    tm = mx.nd.batch_dot(lhs=tv, rhs=tvt)
    tm = mx.nd.square(tm)
    tmm2 = mx.nd.mean(tm, axis=(1,2))
    ## should we add tmm2?
    diff = smm - 2 * tmm + tmm2
    return diff

s = mx.nd.random_normal(shape=(2, 3, 1, 3))
#t = mx.nd.random_normal(shape=(2, 3, 1, 3))
t = s
diff = get_mmd(s, t)

print diff

diff2 = get_mmd2(s, t)
print diff2
```

**Comment by huangzehao** [comment]
We don't calculate the teacher term since it has not contribution to the backpropagation of student network.

**Comment by xmfbit** [comment]
Ok. I got it. One more question (I am a newbie to MXNet): Why don't you use `normalization='batch'` when getting MDD loss? https://github.com/TuSimple/neuron-selectivity-transfer/blob/master/symbol/transfer.py#L38

Because the MDD loss for the mini batch is `L = 1/N * \sum_{i=1}^{N} l_i`, where `N` is the batch size. Thank you!

**Comment by huangzehao** [comment]
The normalization of batch size is done in optimizer. 
https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/module/module.py#L505
There is a rescale_grad = 1.0/batch_size param in optimizer.

**Comment by ForeverRuri** [comment]
I am doing something about the dataset of Cifar10. I want the code with version of Cifar-10 and the Cifar-10 dataset accpetable of MXNET
Thanks a log!

**Comment by ForeverRuri** [comment]
@huangzehao
